# Generated by Django 2.2.10 on 2020-05-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('CS', 'care_seeker'), ('CT', 'care_taker')], max_length=20),
        ),
    ]
