# Generated by Django 2.2.10 on 2020-05-17 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareSeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('rating', models.FloatField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('care_seeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareTaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('rating', models.FloatField(blank=True)),
                ('care_taker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reviews', models.TextField()),
                ('rating', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('care_seeker', models.ManyToManyField(related_name='requests', to='mvt.CareSeeker')),
                ('care_taker', models.ManyToManyField(related_name='requested', to='mvt.CareTaker')),
            ],
        ),
        migrations.CreateModel(
            name='FundTransferRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateTimeField(auto_now=True)),
                ('payer', models.ManyToManyField(related_name='transaction_history', to='mvt.CareSeeker')),
                ('reciver', models.ManyToManyField(related_name='transaction_history', to='mvt.CareTaker')),
            ],
        ),
        migrations.AddField(
            model_name='careseeker',
            name='care_taker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_seekers', to='mvt.CareTaker'),
        ),
    ]
