# Generated by Django 2.2.10 on 2020-05-17 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careseeker',
            name='care_taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_seekers', to='mvt.CareTaker'),
        ),
        migrations.AlterField(
            model_name='careseeker',
            name='wallet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
