# Generated by Django 2.2.10 on 2020-05-19 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvt', '0003_auto_20200517_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='care_seeker',
        ),
        migrations.AddField(
            model_name='request',
            name='care_seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='mvt.CareSeeker'),
        ),
        migrations.RemoveField(
            model_name='request',
            name='care_taker',
        ),
        migrations.AddField(
            model_name='request',
            name='care_taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested', to='mvt.CareTaker'),
        ),
    ]
