# Generated by Django 2.2.10 on 2020-05-20 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mvt', '0004_auto_20200519_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Reviews',
            new_name='msg',
        ),
        migrations.RemoveField(
            model_name='careseeker',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='request',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='caretaker',
            name='active_caretaker_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('AP', 'approved'), ('PE', 'pending'), ('RE', 'rejected'), ('CM', 'completed'), ('AC', 'active')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reviews_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fundtransferrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
