# Generated by Django 2.2.10 on 2020-05-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvt', '0005_auto_20200520_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careseeker',
            name='wallet',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='savings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='fundtransferrecord',
            name='ammount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
