# Generated by Django 2.2.10 on 2020-05-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvt', '0006_auto_20200526_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
