# Generated by Django 2.2.10 on 2020-05-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvt', '0007_auto_20200526_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
