# Generated by Django 2.2.10 on 2020-05-30 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvt', '0010_auto_20200530_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='request_ob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mvt.Request'),
        ),
        migrations.AddField(
            model_name='review',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
